#!/bin/bash
#
# $Id: kolchan-up2deb 111 2019-06-08 22:01:41+04:00 yds $
#
_bashlyk_log=nouse _bashlyk=kolchan . bashlyk

: ${_kolchan_pathLib:=/usr/share/kolchan}

. ${_kolchan_pathLib}/libsys.sh || error NoSuchFile throw -- libsys.sh

kolchan-up2deb::usage() {

  local rc=$? aId
  eval "aId=( $Id: kolchan-up2deb 111 2019-06-08 22:01:41+04:00 yds $ )"

  printf -- "\n  %s %s %s, (c) %s\n\n"                                         \
            "${0##*/}"                                                         \
            "rev${aId[2]}"                                                     \
            "${aId[3]}"                                                        \
            "2016-$(std::date %Y)"

#****h* kolchan/kolchan-up2deb
	cat <<-EOF | tr -d '#'
#  DESCRIPTION
#    Easy way to create or upgrade a source code debian package from an upstream
#    revision. Wrapper for dh_make and uupdate, used shared with other packaging
#    tools  configuration. This  useful  for  automation build process - jenkins
#    pipelines and other CI. Expected  prepared source and configuration file by
#    early runned kolchan-automake
#  USAGE
#    kolchan-up2deb <options>
#  ARGUMENTS
#    -h, --help               - show this usage and exit
#    -c, --config <name>      - set config file (full path or short name)
#    -p, --project <name>     - set project name.  If  no  configuration file is
#                               specified,  the project name is used to generate
#                               the configuration file name.
#    -s, --path-source <path> - select source path. Maybe read from config file.
#                               Default is a current directory.
#    -t, --path-target <path> - select package tree root path. May  be read from
#                               config. Default is a ~/builds
#    -B, --basebuild ...      - use  this  build version for upgrade. Maybe used
#                               special keyword 'init' for create package source
#    -v, --verbosity <number> - set DEBUGLEVEL for debug messages
#    -V, --version            - set  version  for target package source. Special
#                               keyword  'git-tag'  enable  last tag from git as
#                               version
#  USES
#    bashlyk >= 1.94
#  AUTHOR
#    Damir Sh. Yakupov <yds@bk.ru>
#  EXAMPLE
#	mkdir -p ~/src/hello-world
#	cd       ~/src/hello-world
#	cat <<- MAKEFILE > Makefile.am
#	hello_world_SOURCES = hello_world.c
#	bin_PROGRAMS        = hello_world
#	DESTDIR             =
#	MAKEFILE
#	cat <<- HELLOWORLD > hello_world.c
#	#include <stdio.h>
#	int main() {
#		printf( "%s\n", "hello, world!" );
#	}
#	HELLOWORLD
#	cat <<- CHANGELOG > ChangeLog
#	$( date -R )
#	Initial release
#	Version 0.01
#	CHANGELOG
#	hash git 2>/dev/null && git init && git add . && git commit -m "Initial"
#	kolchan-automake && kolchan-up2deb
	EOF

  exit $rc

}
#******
#
#
#
kolchan-up2deb::main() {

  throw on CommandNotFound bc git grep head ls mv uupdate tail tar tr xargs

  local -a a
  local fn fnConfig i iBuildNumber pathBuilds pathSource pathWork s sBaseBuild sBuildVersion sProject sVersion

  CFG cfg
  cfg.bind.cli help{h} path-source{s}: project{p}: path-builds{b}: basebuild{B}: config{c}: version{V}: verbosity{v}:

  [[ $( cfg.getopt help ) ]] && kolchan-up2deb::usage

  DEBUGLEVEL=$( cfg.getopt verbosity )
  std::isNumber $DEBUGLEVEL || DEBUGLEVEL=1

    fnConfig="$( cfg.getopt config    )"
    sProject="$( cfg.getopt project   )"
  sBaseBuild="$( cfg.getopt basebuild )"

  : ${sProject:=$PROJECT}
  if [[ ! $sProject ]]; then
    pathWork="$( pwd )"
    sProject=${pathWork##*/}
  fi

  err::debug 2 make build source package for $sProject

  if   [[ ! $fnConfig && $sProject ]]; then

    cfg.storage.use ${sProject}.project.cfg

  elif [[ $fnConfig ]] && touch $fnConfig 2>/dev/null; then

    cfg.storage.use $fnConfig

  elif [[ $fnConfig ]]; then

    cfg.storage.use ${fnConfig//\//_}.project.cfg

  elif [[ ! $fnConfig && ! $sProject ]]; then

    cfg.storage.use

  fi

  fnConfig=$( cfg.storage.show )

  cfg.load

           s="$( cfg.get     []project   )" &&   sProject=$s
           s="$( cfg.get     []basebuild )" && sBaseBuild=$s
  pathBuilds="$( cfg.get [path]builds    )" || pathBuilds=~/builds
  DEBUGLEVEL=$( cfg.get verbosity )
  std::isNumber $DEBUGLEVEL || DEBUGLEVEL=1
  err::debug 1 project configuration $fnConfig

  if ! pathSource="$( cfg.get [path]source )"; then

    [[ $sProject ]] && pathSource=~/src/${sProject} || error MissingArgument throw -- 'source project undefined, see path-source option'

  fi

  throw on NoSuchDir $pathSource
  [[ $sProject ]] || sProject=${pathSource##*/}

  cfg.set [path]source  = $pathSource
  cfg.set     []project = $sProject

  throw on NoSuchDir $pathBuilds
  cd $pathBuilds || error NotPermitted throw -- $pathBuilds

  rm -rf *.orig

  err::debug 1 "source project $sProject"

  cd $pathSource || error NotPermitted throw -- $pathSource

  git status >/dev/null 2>&1
  if (( $? != 128 )) && ! LC_ALL=C git log 2>&1 | grep '^fatal:.* not have any commits' >/dev/null
  then

    iBuildNumber=$( git shortlog -s | grep -oP '^\s+\d+\s+' | xargs | tr ' ' '+' | bc )

    if ! std::isNumber $iBuildNumber; then
      [[ $PRJ_COMMITS ]] && iBuildNumber=$PRJ_COMMITS
    fi

  fi

  sVersion=$( cfg.get []version )
  [[ $sVersion =~ git.*tag ]] && sVersion=$( git tag -l --sort=version:refname | tail -n 1 )
  if [[ ! $sVersion ]]; then

    if   [[ -s VERSION ]]; then

      a=( $( < VERSION ) )
      sVersion=${a[0]}
      iBuildNumber=${a[1]}

    elif [[ -s ChangeLog ]]; then

      sVersion=$(grep -i version ChangeLog | head -n 1 | xargs | cut -f 2 -d' ')

    fi

  fi

  [[ $sVersion =~ [0-9]+.*[0-9]+ ]] || error InvalidArgument throw -- $sVersion
  std::isNumber $iBuildNumber || iBuildNumber=$( std::date %s )
  sBuildVersion=${sProject}-${sVersion}.${iBuildNumber}

  cd $pathBuilds || error NotPermitted throw -- $pathBuilds

  if [[ $sBaseBuild && ! $sBaseBuild =~ ^init$ && ! -s ${pathBuilds}/${sBaseBuild}/debian/changelog ]]; then

    err::debug 1 reference build ${pathBuilds}/${sBaseBuild} not found or damaged, try search...
    sBaseBuild=''

  fi

  if [[ ! $sBaseBuild ]]; then

    if sBaseBuild=$( cfg.get []last succesfully build ); then
      err::debug 1 "last builded package source ${sBaseBuild} not found or damaged, try search other..."
      [[ -s ${pathBuilds}/${sBaseBuild}/debian/changelog ]] || sBaseBuild=''
    fi

    : ${sBaseBuild:=$( ls -td1 --group-directories-first ${sProject}*/debian/changelog 2>/dev/null | head -n 1 )}

    if [[ $sBaseBuild ]]; then
      sBaseBuild=${sBaseBuild/\/debian\/changelog}
      err::debug 1 "found previous build - ${pathBuilds}/${sBaseBuild} - try use uupdate"
    else
      err::debug 1 "valid previous build not found, try create package source by dh_make"
      sBaseBuild=init
    fi

  fi

  if [[ $sBuildVersion == $sBaseBuild ]]; then

    err::debug 1 used previous build is same a target - ${sBaseBuild}, abort..
    return 1

  fi

  err::debug 2 "used base build $sBaseBuild for package source $sBuildVersion updating"

  SYS::RSYNC rsync
  rsync.title      = "prepare package source $sBuildVersion for $sProject"
  rsync.options    = -aCrv
  rsync.pathSource = ${pathSource}/
  rsync.pathTarget = ${pathBuilds}/${sBuildVersion}
  rsync.onFailure  = throw
  rsync.run

  err::debug 2 "prepare tar archive of the $sBuildVersion"
  tar cfz ${sBuildVersion}.tar.gz $sBuildVersion || error NotExistNotCreated throw "${sBuildVersion}.tar.gz"

  if [[ $sBaseBuild =~ ^init$ ]]; then

    err::debug 1 "try create package source ${pathBuilds}/${sBuildVersion}"
    cd $sBuildVersion || error NotPermitted throw "${pathBuilds}/${sBuildVersion}"
    [[ $( cfg.get []archindep ) == true ]] && s='i' || s='s'
    dh_make -y -${s} -c gpl2 --file ../${sBuildVersion}.tar.gz
    cfg.set [dh_make]status    = $?
    cfg.set [dh_make]timestamp = $( std::date %s )
    cfg.set [path]target       = ${pathBuilds}/${sBuildVersion}

  else

    rm -rf $sBuildVersion
    throw on MissingArgument $sBaseBuild
    throw on NoSuchDir ${pathBuilds}/${sBaseBuild}
    err::debug 2 "update package source - $sBaseBuild -> $sBuildVersion"
    cd $sBaseBuild || error NotPermitted throw "${pathBuilds}/${sBaseBuild}"

    std::temp fn
    err::debugf 1 '%s: ' "start uupdate"

    while read; do
      if [[ $REPLY =~ ^return.code:.(.*)$ ]]; then
        cfg.set [uupdate]status = ${BASH_REMATCH[1]}
        if [[ $( cfg.get [uupdate]status ) != '0' ]]; then
          err::debug 1 "fail.."
          err::debug 1 stderr:
          err::debug 1 && cat $fn 1>&2
          i=1
        else
          err::debug 1 "ok!"
          err::debug 2 "target path ${pathBuilds}/${sBuildVersion}"
          cfg.set [path]target = ${pathBuilds}/${sBuildVersion}
          i=0
        fi
        cfg.set [uupdate]timestamp = $( std::date %s )
      else
        echo $REPLY > $fn
        err::debugf 1 '%s' '.'
      fi
    done< <( LC_ALL=C uupdate ${sBuildVersion}.tar.gz 2>&1; echo "return code: $?" )

  fi

  err::debug 1 status of the preparation target $sBuildVersion from $sBaseBuild:
  cfg.show
  cfg.save
  cfg.free

  if (( i == 0 )); then
    return 0
  else
    cd $pathBuilds && rm -rf $s
    return 1
  fi

}
#
#
#
kolchan-up2deb::main
#
